application: gamers-galore
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: .*
  script: main.app

- url: /gadgets/disney.xml
  static_files: gadgets/disney.xml
  upload: gadgets/disney.xml

- url: /gadgets/wwe.xml
  static_files: gadgets/wwe.xml
  upload: gadgets/wwe.xml

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest